name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Compile extension
      run: npm run compile
      
    - name: Verify package can be built (Ubuntu only)
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
      run: |
        npm install -g @vscode/vsce
        vsce package --out test-build.vsix
        
    - name: Upload test build artifact (Ubuntu only)
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: test-build-${{ github.sha }}
        path: test-build.vsix
        retention-days: 7
