name: Release Extension

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Compile extension
      run: npm run compile
      
    - name: Install vsce (VS Code Extension CLI)
      run: npm install -g @vscode/vsce
      
    - name: Extract version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
      
    - name: Update package.json version to match tag
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        TARGET_VERSION=${{ steps.get_version.outputs.VERSION }}
        echo "Current version: $CURRENT_VERSION"
        echo "Target version: $TARGET_VERSION"
        if [ "$CURRENT_VERSION" != "$TARGET_VERSION" ]; then
          npm version $TARGET_VERSION --no-git-tag-version
          echo "Version updated from $CURRENT_VERSION to $TARGET_VERSION"
        else
          echo "Version is already $TARGET_VERSION, skipping update"
        fi
        
    - name: Package extension
      run: vsce package --out jsonbro-${{ steps.get_version.outputs.VERSION }}.vsix
      
    - name: Create checksum
      run: |
        sha256sum jsonbro-${{ steps.get_version.outputs.VERSION }}.vsix > jsonbro-${{ steps.get_version.outputs.VERSION }}.vsix.sha256
        cat jsonbro-${{ steps.get_version.outputs.VERSION }}.vsix.sha256
      
    - name: Upload VSIX and checksum to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} \
          jsonbro-${{ steps.get_version.outputs.VERSION }}.vsix \
          jsonbro-${{ steps.get_version.outputs.VERSION }}.vsix.sha256
        
    - name: Store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-package-${{ steps.get_version.outputs.VERSION }}
        path: |
          *.vsix
          *.sha256
        retention-days: 90
